spring.application.name=EMS
#spring.config.import=optional:file:.env[.properties]
spring.datasource.url=your_postgresql_url_here
spring.datasource.username=your_db_username_here
spring.datasource.password=your_db_password_here
spring.jpa.properties.hibernate.default_schema=erp
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
file.upload-dir=ems-service/uploads/documents
file.payslip-dir=ems-service/uploads/payslips
server.address=0.0.0.0
server.port=8081
jwt.secret=your_jwt_secret_here
spring.cloud.compatibility-verifier.enabled=false
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

notification.service.url=http://localhost:8082
internal.api.secret=your_internal_api_secret_here