# ---------------------------
# SPRING BASIC CONFIG
# ---------------------------
spring.application.name=ticket-service

# ---------------------------
# H2 CONSOLE
# ---------------------------
spring.h2.console.enabled=true

# ---------------------------
# JWT CONFIG
# ---------------------------
jwt.secret=your_jwt_secret_here
jwt.expiration=86400000

# ---------------------------
# AUTH SERVICE
# ---------------------------
auth.service.url=http://localhost:8080

# ---------------------------
# SERVER
# ---------------------------
server.address=0.0.0.0
server.port=8084

# Notification
notification.service.url=http://localhost:8082
internal.api.secret=your_internal_api_secret_here

# ---------------------------
# DATABASE (POSTGRES)
# ---------------------------
spring.datasource.url=your_postgresql_url_here
spring.datasource.username=your_db_username_here
spring.datasource.password=your_db_password_here
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------------------
# JPA / HIBERNATE
# ---------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=erp

# ---------------------------
# LOGGING
# ---------------------------
logging.level.org.springframework.security=DEBUG
logging.level.com.erp.Ticketing=DEBUG
logging.level.org.springframework.web.servlet.handler.HandlerMappingIntrospector=ERROR

# ---------------------------
# ACTUATOR
# ---------------------------
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,db