package com.app.EMS.entity;

public enum NotificationType {

    /* ================= EMS ================= */

    EMPLOYEE_CREATED,
    EMPLOYEE_DEACTIVATED,

    LEAVE_REQUEST,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_UPDATED,
    LEAVE_CANCELLED,

    ATTENDANCE_MARKED,

    SALARY_STRUCTURE_CREATED,
    SALARY_STRUCTURE_UPDATED,
    SALARY_STRUCTURE_APPROVED,
    SALARY_STRUCTURE_REJECTED,
    SALARY_STRUCTURE_DELETED,

    PAYROLL_GENERATED,
    PAYSLIP_GENERATED,
    SALARY_PAID
}