spring.application.name=InventoryMgt
spring.datasource.url=your_postgresql_url_here
spring.datasource.username=your_db_username_here
spring.datasource.password=your_db_password_here

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Ensure single-line SQL (no formatting)
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.org.springframework.security=DEBUG

spring.jpa.properties.hibernate.default_schema=public

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

aws.access.key=your_aws_access_key_here
aws.secret.key=your_aws_secret_key_here
cloud.aws.credentials.region=ap-south-1
cloud.aws.s3.bucket-name=anjali-assets-2026

server.address=0.0.0.0
server.port=8083

spring.cloud.compatibility-verifier.enabled=false

auth.service.url=http://localhost:8080
notification.service.url=http://localhost:8082

jwt.secret=your_jwt_secret_here
internal.api.secret=your_internal_api_secret_here

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Logging
logging.level.root=INFO
logging.level.com.erp=DEBUG
logging.level.org.springframework=INFO